name: Download Godot
description: Download appropriate Godot executable
inputs:
  version:
    description: The Godot version to download
    required: true
outputs:
  executable:
    description: The downloaded Godot executable
    value: ${{ steps.unzip-godot.outputs.executable }}
runs:
  using: composite
  steps:
    - name: Linux File Pattern
      if: runner.os == 'Linux'
      shell: bash
      run: echo "FILE=(linux\.x86_64|x11\.64)" >> $GITHUB_ENV

    - name: MacOS File Pattern
      if: runner.os == 'macOS'
      shell: bash
      run: echo "FILE=([^m][^o][^n][^o][^_])(macos|osx)\.universal" >> $GITHUB_ENV

    - name: Windows File Pattern
      if: runner.os == 'Windows'
      shell: bash
      run: echo "FILE=win64.exe" >> $GITHUB_ENV

    - name: Download Godot
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: godotengine/godot
        version: tags/${{ inputs.version }}
        regex: true
        target: './' # Defaults to regex prepended to filename
        file: ${{ env.FILE }}

    - name: Unzip Godot
      id: unzip-godot
      shell: bash
      run: |
        ls
        zip_file=$( ls | grep -E '${{ env.FILE }}' )
        echo "$zip_file"
        unzip "$zip_file"
        rm "$zip_file"
        echo "executable=$( ls | grep -E '${{ env.FILE }}' )"
        echo "executable=$( ls | grep -E '${{ env.FILE }}' )" >> $GITHUB_OUTPUT
