name: Sconstruct Build
description: Build GDExtension/GDNative addon with Sconstruct
inputs:
  platform:
    description: The Godot platform to build
    required: true
  target:
    description: The Godot target to build
    required: true
  godot-major:
    description: The major version of Godot being targeted used in cache name
    required: true
  scons-flags:
    description: Additional Sconstruct flags
    default: ''
  cache-prefix:
    description: Prefix prepended to cache name
    default: ''
  scons-cache:
    description: The Sconstruct cache path
    default: ${{ github.workspace }}/.scons-cache/
runs:
  using: composite
  steps:
    - name: Cache Base Name
      id: cache-name
      shell: bash
      run: echo "name=${{ inputs.cache-prefix }}${{ inputs.platform }}-${{ inputs.godot-major }}-${{ github.workflow }}" >> $GITHUB_OUTPUT

    - name: Cache Scons
      uses: actions/cache@v3
      with:
        path: ${{ inputs.scons-cache }}
        key: scons-${{ steps.cache-name.outputs.name }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          scons-${{ steps.cache-name.outputs.name }}-${{ github.ref }}-${{ github.sha }}
          scons-${{ steps.cache-name.outputs.name }}-${{ github.ref }}
          scons-${{ steps.cache-name.outputs.name }}

    - name: MSVC Developer Command Prompt
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Scons Build
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      env:
        SCONS_CACHE: ${{ inputs.scons-cache }}
      run: scons platform=${{ inputs.platform }} target=${{ inputs.target }} ${{ inputs.scons-flags }}
