name: Export Tests
description: Export and run test project
inputs:
  executable:
    description: The Godot executable in CWD
    required: true
runs:
  using: composite
  steps:
    - name: Linux Export Details
      if: runner.os == 'Linux'
      shell: bash
      run: echo "EXTENSION=x86_64" >> $GITHUB_ENV

    - name: MacOS Export Details
      if: runner.os == 'macOS'
      shell: bash
      run: echo "EXTENSION=app" >> $GITHUB_ENV

    - name: Windows Export Details
      if: runner.os == 'Windows'
      shell: bash
      run: echo "EXTENSION=exe" >> $GITHUB_ENV

    - name: Export
      shell: bash
      run: |
        ./${{ inputs.executable }} --verbose --headless --no-window --export-release --path examples/wasm-test "${{ runner.os }}" ../../WasmTest.${{ env.EXTENSION }}
        echo "EXECUTABLE=WasmTest.${{ env.EXTENSION }}" >> $GITHUB_ENV
        echo "ls ."
        ls
        echo "ls examples/wasm-test"
        ls examples/wasm-test

    - name: MacOS Executable
      if: runner.os == 'macOS'
      shell: bash
      run: echo "EXECUTABLE=WasmTest.app/Contents/MacOS/WasmTest" >> $GITHUB_ENV

    - name: Run Tests
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: ./${{ env.EXECUTABLE }} --headless --no-window -- --key=val
