name: Build Addon
description: Build GDExtension/GDNative addon with Sconstruct
inputs:
  platform:
    description: The Godot platform to build
    required: true
  target:
    description: The Godot target to build
    required: true
  scons-cache:
    description: The Sconstruct cache path
    default: "${{ github.workspace }}/.scons-cache/"
runs:
  using: composite
  steps:
    - name: Scons Build
      shell: bash
      env:
        SCONS_CACHE: ${{ inputs.scons-cache }}
        SCONS_CACHE_LIMIT: 6000 # Limit to 6 GiB
      run: scons p=${{ inputs.platform }} target=${{ inputs.target }}
