name: Build Addon
description: Build GDExtension/GDNative addon with Sconstruct
inputs:
  platform:
    description: The Godot platform to build
    required: true
  target:
    description: The Godot target to build
    required: true
  scons-flags:
    description: Additional Sconstruct flags
    default: ''
  scons-cache:
    description: The Sconstruct cache path
    default: ${{ github.workspace }}/.scons-cache/
runs:
  using: composite
  steps:
    - name: Scons Build
      shell: bash
      env:
        SCONS_CACHE: ${{ inputs.scons-cache }}
      run: scons p=${{ inputs.platform }} target=${{ inputs.target }} ${{ inputs.scons-flags }}
