name: Build Addon
description: Build GDExtension/GDNative addon with Sconstruct
inputs:
  platform:
    description: The Godot platform to build.
    required: false
  scons-cache:
    description: The Sconstruct cache path
    default: "${{ github.workspace }}/.scons-cache/"
runs:
  using: composite
  steps:
    - name: Scons Build
      env:
        SCONS_CACHE: ${{ inputs.scons-cache }}
        SCONS_CACHE_LIMIT: 6000 # Limit to 6 GiB
      run: scons p=${{ inputs.platform }} target=template_release
