name: Sconstruct Cache
description: Cache Sconstruct build cache
inputs:
  scons-cache:
    description: The Sconstruct cache path
    default: "${{ github.workspace }}/.scons-cache/"
runs:
  using: composite
  steps:
    - name: Load Cache
      uses: actions/cache@v3
      env:
        CACHE_NAME: ${{ env.PLATFORM }}-${{ env.GODOT_VERSION }}-${{ github.job }}
      with:
        path: ${{ inputs.scons-cache }}
        key: ${{ env.CACHE_NAME }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ env.CACHE_NAME }}-${{ github.ref }}-${{ github.sha }}
          ${{ env.CACHE_NAME }}-${{ github.ref }}
          ${{ env.CACHE_NAME }}
