name: Sconstruct Cache
description: Cache Sconstruct build cache
inputs:
  cache-name:
    description: The cache base name
    default: ${{ env.PLATFORM }}-${{ env.GODOT_VERSION }}-${{ github.job }}
  scons-cache:
    description: The Sconstruct cache path
    default: "${{ github.workspace }}/.scons-cache/"
runs:
  using: composite
  steps:
    - name: Load Cache
      uses: actions/cache@v3
      with:
        path: ${{ inputs.scons-cache }}
        key: ${{ inputs.cache-name }}-${{ env.GODOT_VERSION }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ inputs.cache-name }}-${{ env.GODOT_VERSION }}-${{ github.ref }}-${{ github.sha }}
          ${{ inputs.cache-name }}-${{ env.GODOT_VERSION }}-${{ github.ref }}
          ${{ inputs.cache-name }}-${{ env.GODOT_VERSION }}
