name: Run Tests
description: Run the Godot Wasm test project
inputs:
  executable:
    description: The Godot executable in CWD
    required: true
runs:
  using: composite
  steps:
    - name: Run Tests
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: ./${{ inputs.executable }} --headless --no-window --debug --path examples/wasm-test -- --key=val
